#!/usr/bin/env python3
"""
Build a tailored resume and cover letter for one role, from a role spec.

    python build_docs.py roles/companyh.json

The role spec is a small JSON file:
{
  "key": "companyh",
  "company": "Company H",
  "role": "MBA Consultant (2027 Grads)",
  "location": "New York City or Boston",
  "folder": "Company H - MBA Consultant 2027",
  "addressee": "Dear Hiring Team,",
  "date": "September 20, 2026",
  "req": "",
  "coursework": "Coursework: ...",
  "skills": "Skills: ...",
  "felix": ["bullet 1", "bullet 2", "bullet 3"],
  "letter": ["para 1", "para 2", "para 3", "para 4"]
}

Anything omitted falls back to what is already in the v5 master.
Resume comes from the v5 master, letter from the same template every time.
Then run review.py before the PDFs are made.
"""
import json, os, shutil, sys
import docx

HERE = os.path.dirname(os.path.abspath(__file__))
FT = os.environ.get("CAREER_DIR", "<CAREER_DIR>")  # documents and trackers live there, code lives here
RES = os.path.join(FT, "01. Resume and Cover Letters")
MASTER = os.path.join(RES, "Joaquin Laria - Resume (FT 2027) v5.docx")
LETTER_TPL = os.path.join(RES, "Company J - Associate PM 2027",
                          "Joaquin Laria - Cover Letter (Company J - Associate PM 2027).docx")

EM = chr(8212)
BANNED = ("delve", "crucial", "robust", "comprehensive", "nuanced", "multifaceted",
          "spearhead", "passionate about", "excited about the opportunity", "seamless",
          "cutting-edge", "tapestry", "landscape", "realm", "testament", "underscore",
          "pivotal", "resonate", "meticulous", "utilize", "furthermore", "moreover",
          "leverage", "i am writing to apply")
AI_WORDS = ("claude", "chatgpt", "an agent i built", "submitted by a system",
            "generated by ai", "written by ai", "automated application")


def set_text(par, text):
    if not par.runs:
        par.text = text
        return
    par.runs[0].text = text
    for r in par.runs[1:]:
        r.text = ""


def voice_check(spec):
    blob = " ".join(spec.get("letter", []) + spec.get("felix", []) +
                    [spec.get("coursework", ""), spec.get("skills", "")])
    bad = []
    if EM in blob:
        bad.append("em dash")
    low = blob.lower()
    bad += [w for w in BANNED if w in low]
    bad += [f"AI mention: {w}" for w in AI_WORDS if w in low]
    if bad:
        sys.exit("VOICE CHECK FAILED, nothing written: " + ", ".join(bad))
    print("voice check passed")


def build_resume(spec, out_dir):
    dst = os.path.join(out_dir, f"Joaquin Laria - Resume ({spec['folder']}).docx")
    shutil.copyfile(MASTER, dst)
    d = docx.Document(dst)
    ps = d.paragraphs

    for p in ps:
        t = p.text.strip()
        if spec.get("coursework") and t.startswith("Coursework:"):
            set_text(p, spec["coursework"])
        elif spec.get("skills") and t.startswith("Skills:"):
            set_text(p, spec["skills"])

    if spec.get("felix"):
        start = next((i for i, p in enumerate(ps)
                      if "new bets" in p.text.lower() and "product manager" in p.text.lower()), None)
        if start is None:
            sys.exit("could not find the Felix title line in the master")
        n, i = 0, start + 1
        while i < len(ps) and n < len(spec["felix"]):
            if ps[i].text.strip():
                set_text(ps[i], spec["felix"][n]); n += 1
            i += 1
    d.save(dst)
    print("resume ->", os.path.basename(dst))
    return dst


def build_letter(spec, out_dir):
    dst = os.path.join(out_dir, f"Joaquin Laria - Cover Letter ({spec['folder']}).docx")
    shutil.copyfile(LETTER_TPL, dst)
    d = docx.Document(dst)
    ps = d.paragraphs
    if len(ps) < 16:
        sys.exit(f"letter template has {len(ps)} paragraphs, expected 16")

    re_line = spec.get("re") or f"Re: {spec['role']}, {spec['location']}"
    if spec.get("req"):
        re_line += f" (Req {spec['req']})"

    head = [spec.get("date", "September 20, 2026"), spec["company"],
            spec.get("team", "Recruiting"), re_line, spec["addressee"]]
    body = spec["letter"]
    slots = [3, 4, 5, 7, 8] + list(range(9, 9 + len(body)))
    vals = head + body
    for slot, text in zip(slots, vals):
        set_text(ps[slot], text)
    # blank any unused body paragraphs so a short letter does not keep old text
    for extra in range(9 + len(body), 14):
        set_text(ps[extra], "")
    set_text(ps[14], "Sincerely,")
    set_text(ps[15], "Joaquin Laria")
    d.save(dst)
    print("letter ->", os.path.basename(dst))
    return dst


def main():
    spec = json.load(open(sys.argv[1], encoding="utf-8"))
    voice_check(spec)
    out_dir = os.path.join(RES, spec["folder"])
    os.makedirs(out_dir, exist_ok=True)
    r = build_resume(spec, out_dir)
    c = build_letter(spec, out_dir)
    print("OUT:", out_dir)
    print("NEXT: python review.py --resume", f'"{r}"', "--letter", f'"{c}"',
          "--company", f'"{spec["company"]}"')


if __name__ == "__main__":
    main()
