#!/usr/bin/env python3
"""
The reviewer. Grades a resume and cover letter against GOLD.md before anything
becomes a PDF, and refuses to pass work that breaks a hard rule.

    python review.py --resume <resume.docx> --letter <letter.docx> [--jd jd.txt] [--company "Name"]

Exit code 0 means it passed. Exit code 1 means a hard gate failed and the
documents should not be sent.

Hard gates fail the run. Warnings are printed and do not.
"""
import argparse, json, os, re, sys

import docx

HERE = os.path.dirname(os.path.abspath(__file__))

EM_DASH = chr(8212)
EN_DASH = chr(8211)

BANNED = [
    "delve", "crucial", "robust", "comprehensive", "nuanced", "multifaceted",
    "spearhead", "passionate about", "excited about the opportunity", "seamless",
    "cutting-edge", "tapestry", "landscape", "realm", "testament", "underscore",
    "pivotal", "resonate", "meticulous", "utilize", "furthermore", "moreover",
    "in today's", "ever-evolving", "deep dive", "i am writing to apply",
    "i believe i would be a great fit", "leverage",
]

# Mentioning AI authorship anywhere is an instant fail. Joaquin, 2026-09-20.
AI_AUTHORSHIP = [
    "written by ai", "generated by ai", "with the help of ai", "using claude",
    "built with claude", "an agent i built", "a system i built that", "chatgpt wrote",
    "submitted by a system", "this application was submitted by",
    "automated application", "ai wrote",
]

FORBIDDEN_CLAIMS = [
    ("generally available", "Tap to Collect never reached GA. Prototyped, piloted, handed off."),
    ("general availability", "Tap to Collect never reached GA."),
    ("overseer", "internal Felix term"), ("nightveil", "internal Felix term"),
    ("paymentscentral", "internal Felix term"), ("gotham", "internal Felix term"),
    ("kapso", "internal Felix term"), ("clabe", "internal Felix term"),
    ("tubp", "internal Felix term"),
    ("healthcare", "healthcare framing is closed"),
    ("health-tech", "healthcare framing is closed"),
]

PRONOUNS = re.compile(r"\b(I|my|me|we|our|us)\b")

# CAPD action verbs, accomplishments list first since those are the strong ones
STRONG_VERBS = """accelerated achieved attained completed conceived convinced discovered
doubled effected eliminated expanded expedited founded improved increased initiated
innovated introduced invented launched mastered originated overcame overhauled pioneered
reduced resolved revitalized strengthened transformed upgraded built shipped designed
delivered drove cut won priced turned recovered ran coded moved administered analyzed
coordinated developed directed evaluated executed organized oversaw planned produced
recommended reorganized reviewed supervised authored collaborated drafted formulated
influenced negotiated persuaded promoted proposed clarified collected critiqued
diagnosed examined extracted identified inspected interpreted interviewed investigated
summarized surveyed assembled calculated devised engineered fabricated maintained
operated programmed solved systematized adapted advised coached communicated conducted
enabled encouraged explained facilitated guided informed instructed lectured trained
conceptualized created customized established fashioned illustrated instituted
integrated performed proved revised set shaped streamlined structured tabulated
validated assessed assisted counseled demonstrated educated familiarized inspired
motivated provided referred reinforced represented supported verified approved arranged
catalogued classified compiled dispatched filed generated implemented monitored ordered
prepared processed purchased recorded retrieved screened specified""".split()

STOP = set("""a an the and or but if of to in on for with at by from as is are was were be
been being this that these those it its their his her our your my we i you they he she
not no than then so such over under into out up down more most less least very can will
would could should may might must have has had do does did about across after all also
any because before both during each few how just like new now only other own same some
through too was what when where which while who why""".split())


def words(t):
    return re.findall(r"[a-zA-Z][a-zA-Z0-9\-\+/&\.]*", t.lower())


def read_docx(p):
    d = docx.Document(p)
    return [x.text.strip() for x in d.paragraphs if x.text.strip()]


class Report:
    def __init__(self):
        self.fail = []
        self.warn = []
        self.ok = []

    def F(self, where, msg):
        self.fail.append(f"[{where}] {msg}")

    def W(self, where, msg):
        self.warn.append(f"[{where}] {msg}")

    def P(self, msg):
        self.ok.append(msg)


def common_checks(r, where, text):
    low = text.lower()
    if EM_DASH in text:
        r.F(where, f"em dash found {EM_DASH!r}. Hard rule, never use one.")
    for b in BANNED:
        if b in low:
            r.F(where, f"banned phrase: {b!r}")
    for a in AI_AUTHORSHIP:
        if a in low:
            r.F(where, f"mentions AI authorship: {a!r}. Never allowed anywhere.")
    for term, why in FORBIDDEN_CLAIMS:
        if term in low:
            r.F(where, f"forbidden claim {term!r}: {why}")


def check_numbers(r, where, text, bullets):
    """Every number on the page must trace to BULLETS.json."""
    allowed = set()
    blob = json.dumps(bullets)
    for n in re.findall(r"\d[\d,\.]*", blob):
        allowed.add(n.rstrip(".").replace(",", ""))
    for n in re.findall(r"\d[\d,\.]*", text):
        clean = n.rstrip(".").replace(",", "")
        if len(clean) <= 2:            # small ints, weeks, counts, years fragments
            continue
        if clean in allowed:
            continue
        if re.fullmatch(r"(19|20)\d\d", clean):   # a year
            continue
        ctx = text[max(0, text.find(n) - 90): text.find(n) + 90].lower()
        if any(k in ctx for k in ("you ", "your ", "company", "brands", "employees",
                                  "clients", "fortune", "portfolio")):
            continue                    # a fact about the employer, not about him
        r.W(where, f"number {n!r} is not in BULLETS.json. Verify it or remove it.")


LABEL_LINE = re.compile(
    r"^(coursework|clubs?|skills?|languages?|interests?|gpa|education|experience|"
    r"additional information|certifications?|awards?|honors?)\b[:\s]", re.I)


def is_company_header(p):
    """Company or school line: mostly capitals, or a line with a tabbed date."""
    letters = [c for c in p if c.isalpha()]
    if letters and sum(1 for c in letters if c.isupper()) / len(letters) > 0.7:
        return True
    return "\t" in p


def resume_bullets(ps):
    """A bullet is an achievement line. Not the header block, not a section
    label, not a company or title line, and not the italic company descriptor
    that follows a company name."""
    out = []
    prev_header = False
    for i, p in enumerate(ps):
        header_now = is_company_header(p)
        if i < 3:                       # name, contact, first section word
            prev_header = header_now
            continue
        if header_now or LABEL_LINE.match(p) or "\t" in p:
            prev_header = True
            continue
        if prev_header:                 # the one-line company descriptor
            prev_header = False
            continue
        if len(p.split()) >= 8:
            out.append(p)
        prev_header = False
    return out


def review_resume(path, bullets, jd_text, r):
    ps = read_docx(path)
    text = "\n".join(ps)
    # skip the contact block for number checking: phone and zip are not claims
    claims_text = "\n".join(ps[3:])
    common_checks(r, "resume", text)
    check_numbers(r, "resume", claims_text, bullets)

    cand = resume_bullets(ps)
    n_long, n_weak_verb, n_pronoun, n_two_ideas = 0, 0, 0, 0
    for b in cand:
        w = b.split()
        if len(w) > 34:
            r.W("resume", f"bullet is over two lines ({len(w)} words): {b[:70]}...")
            n_long += 1
        first = re.sub(r"[^a-zA-Z]", "", w[0]).lower()
        if first and first not in STRONG_VERBS and not first.endswith("ed"):
            r.W("resume", f"does not start with an action verb ({w[0]!r}): {b[:60]}...")
            n_weak_verb += 1
        if PRONOUNS.search(b):
            r.F("resume", f"first-person pronoun, CAPD forbids it: {b[:70]}...")
            n_pronoun += 1
        if b.lower().count(" and ") >= 2:
            r.W("resume", f"two ideas in one bullet, consider splitting: {b[:70]}...")
            n_two_ideas += 1
        if b.count(",") >= 5:
            r.W("resume", f"{b.count(',')} commas, it will not be read: {b[:70]}...")

    r.P(f"resume: {len(cand)} bullets checked, {n_long} over length, "
        f"{n_weak_verb} weak openers, {n_pronoun} pronoun violations, {n_two_ideas} double-idea")

    if jd_text:
        keyword_report(r, "resume", text, jd_text)


def review_letter(path, bullets, jd_text, company, r):
    ps = read_docx(path)
    text = "\n".join(ps)
    low = text.lower()
    common_checks(r, "letter", text)
    check_numbers(r, "letter", "\n".join(ps[3:]), bullets)

    wc = len(text.split())
    if wc > 620:
        r.F("letter", f"{wc} words, will not fit one page. CAPD hard rule. Cut to under 600.")
    elif wc > 520:
        r.W("letter", f"{wc} words, close to the one-page limit.")
    else:
        r.P(f"letter: {wc} words, fits one page")

    # salutation
    sal = next((p for p in ps if p.lower().startswith("dear") or re.match(r"^[A-Z][a-z]+( y | and )", p)), "")
    if not sal:
        r.F("letter", "no salutation found.")
    elif re.search(r"dear (hiring team|hiring manager|sir|madam|to whom)", sal.lower()):
        r.W("letter", f"generic salutation {sal!r}. All four of his best letters name a person. "
                      "Check PROFILE.md target list for a contact.")
    else:
        r.P(f"letter: addressed to a person, {sal!r}")

    # opening must not be a template line
    body = [p for p in ps if len(p.split()) > 20]
    if body:
        first = body[0].lower()
        if first.startswith(("i am writing", "i would like to apply", "please accept")):
            r.F("letter", "opens with a template line. His best letters open on a specific moment.")
        else:
            r.P("letter: opening is not a template line")
        for p in body:
            for s in re.split(r"(?<=[.!?])\s+", p):
                if len(s.split()) > 45:
                    r.W("letter", f"sentence of {len(s.split())} words: {s[:70]}...")

    if company and company.lower() not in low:
        r.F("letter", f"never names the company ({company!r}). CAPD requires it be tailored.")
    elif company:
        c = low.count(company.lower())
        r.P(f"letter: names {company} {c} time(s)")
        if c < 2:
            r.W("letter", "names the company only once. His best letters name it three or more times.")

    # does it carry at least one hard number
    if not re.search(r"\d", text):
        r.F("letter", "contains no numbers at all. Every one of his best letters is concrete.")

    # named contacts, the strongest signal in his own letters
    if not re.search(r"\b(spoke|talked|met|connected|conversation|shared)\b", low):
        r.W("letter", "no reference to a person he spoke to. Three of his four best letters have one.")

    if jd_text:
        keyword_report(r, "letter", text, jd_text)


def keyword_report(r, where, doc_text, jd_text):
    """Coverage of the JD's own vocabulary, with a ceiling so it cannot be padded."""
    junk = {"nbsp", "data", "section", "start", "end", "strong", "href", "http", "https",
            "www", "com", "class", "span", "div", "amp", "quot", "li", "ul", "br"}
    jd = [w for w in words(jd_text)
          if w not in STOP and w not in junk and len(w) > 3 and not w.startswith("data-")]
    freq = {}
    for w in jd:
        freq[w] = freq.get(w, 0) + 1
    top = [w for w, c in sorted(freq.items(), key=lambda x: -x[1])[:35]]
    have = [w for w in top if w in set(words(doc_text))]
    pct = round(100 * len(have) / max(1, len(top)))
    r.P(f"{where}: JD keyword coverage {pct}% ({len(have)}/{len(top)})")
    if pct < 35:
        r.W(where, f"only {pct}% keyword coverage. Missing: {', '.join(w for w in top if w not in have)[:160]}")

    # keyword soup guard: no sentence should be a pile of JD terms
    for s in re.split(r"(?<=[.!?\n])\s+", doc_text):
        sw = words(s)
        if len(sw) < 8:
            continue
        hits = sum(1 for w in sw if w in top)
        if hits >= 7 and hits / len(sw) > 0.35:
            r.W(where, f"reads as keyword soup ({hits} JD terms in one sentence): {s[:80]}...")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--resume")
    ap.add_argument("--letter")
    ap.add_argument("--jd", help="path to a text file with the job description")
    ap.add_argument("--company")
    a = ap.parse_args()

    bullets = json.load(open(os.path.join(HERE, "BULLETS.json"), encoding="utf-8"))
    jd_text = open(a.jd, encoding="utf-8").read() if a.jd and os.path.exists(a.jd) else ""

    r = Report()
    if a.resume:
        review_resume(a.resume, bullets, jd_text, r)
    if a.letter:
        review_letter(a.letter, bullets, jd_text, a.company, r)

    print("=" * 74)
    print("REVIEW")
    print("=" * 74)
    for m in r.ok:
        print("  ok    ", m)
    if r.warn:
        print("\nWARNINGS, judgement calls, they do not block")
        for m in r.warn:
            print("  warn  ", m)
    if r.fail:
        print("\nHARD FAILURES, these block sending")
        for m in r.fail:
            print("  FAIL  ", m)
        print(f"\nVERDICT: DO NOT SEND. {len(r.fail)} hard failure(s), {len(r.warn)} warning(s).")
        sys.exit(1)
    print(f"\nVERDICT: PASS. 0 hard failures, {len(r.warn)} warning(s).")


if __name__ == "__main__":
    main()
